require("prototypes.ammo-categories")
require("prototypes.item")
require("prototypes.recipe")
require("prototypes.technology")
require("prototypes.entity.projectiles")
require("prototypes.entity.spell-animations")